#!/bin/bash
# Least-privilege Postgres roles (plan §7 "DB roles"). Runs once, on first volume init.
# Passwords come from the container env (generated by `pnpm env:init`), never from git.
set -euo pipefail

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  -v db="$POSTGRES_DB" \
  -v migrator_pw="$PG_MIGRATOR_PASSWORD" \
  -v web_pw="$PG_WEB_PASSWORD" \
  -v worker_pw="$PG_WORKER_PASSWORD" \
  -v readonly_pw="$PG_READONLY_PASSWORD" <<'SQL'
-- Login roles: no superuser, no role/db creation.
CREATE ROLE app_migrator LOGIN PASSWORD :'migrator_pw' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE app_web      LOGIN PASSWORD :'web_pw'      NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE app_worker   LOGIN PASSWORD :'worker_pw'   NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE app_readonly LOGIN PASSWORD :'readonly_pw' NOSUPERUSER NOCREATEDB NOCREATEROLE;

REVOKE ALL ON DATABASE :"db" FROM PUBLIC;
GRANT CONNECT ON DATABASE :"db" TO app_migrator, app_web, app_worker, app_readonly;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

-- Extensions (plan §5) are installed by the superuser, once.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- All app tables live in schema "app", owned by the migrator (DDL only via migrations).
CREATE SCHEMA app AUTHORIZATION app_migrator;
GRANT USAGE ON SCHEMA app TO app_web, app_worker, app_readonly;

ALTER DEFAULT PRIVILEGES FOR ROLE app_migrator IN SCHEMA app
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_web, app_worker;
ALTER DEFAULT PRIVILEGES FOR ROLE app_migrator IN SCHEMA app
  GRANT SELECT ON TABLES TO app_readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE app_migrator IN SCHEMA app
  GRANT USAGE, SELECT ON SEQUENCES TO app_web, app_worker;

-- Per-role guardrails (SR-X.29).
ALTER ROLE app_migrator SET search_path = app, public;
ALTER ROLE app_web      SET search_path = app, public;
ALTER ROLE app_worker   SET search_path = app, public;
ALTER ROLE app_readonly SET search_path = app, public;
ALTER ROLE app_web      SET statement_timeout = '5s';
ALTER ROLE app_readonly SET statement_timeout = '5s';
ALTER ROLE app_worker   SET statement_timeout = '60s';
ALTER ROLE app_readonly SET default_transaction_read_only = on;
SQL
