import {
  createDb,
  createListing,
  createOrder,
  markOrderPaid,
  seedSample,
  setListingStatus,
} from '@gth/db';
import { type TestDatabase, startTestDatabase } from '@gth/db/test';
import type { FastifyInstance } from 'fastify';
import Stripe from 'stripe';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { buildApp } from '../app.js';
import { type ApiConfig, loadConfig } from '../config.js';
import { createStripeClient } from '../payments/stripe.js';

/**
 * Stripe's webhooks (SR-5.2, AC-5.2).
 *
 * **The signature verification here is real.** `constructEvent` is Stripe's own, the headers
 * are generated by Stripe's own helper, and the comparison is local HMAC — no network is
 * involved, and nothing is faked on the half of this that decides whether to believe a claim
 * that money moved. A stub would have proved only that a stub returns what it was told to.
 */
const WEBHOOK_SECRET = 'whsec_test_secret_for_signature_verification';
const config: ApiConfig = loadConfig({ LOG_LEVEL: 'silent', NODE_ENV: 'test' });

let tdb: TestDatabase;
let workerPool: ReturnType<typeof createDb>;
let webPool: ReturnType<typeof createDb>;
let app: FastifyInstance;

const SELLER = 'webhook-seller';
const ACCOUNT = 'acct_webhooktest';

/** A signed delivery, exactly as Stripe would send it. */
function delivery(event: Record<string, unknown>, options: { secret?: string; at?: number } = {}) {
  const payload = JSON.stringify(event);
  const header = Stripe.webhooks.generateTestHeaderString({
    payload,
    secret: options.secret ?? WEBHOOK_SECRET,
    ...(options.at === undefined ? {} : { timestamp: options.at }),
  });
  return { payload, header };
}

function accountUpdated(id: string, charges: boolean, payouts: boolean, eventId = 'evt_1') {
  return {
    id: eventId,
    object: 'event',
    type: 'account.updated',
    data: { object: { id, object: 'account', charges_enabled: charges, payouts_enabled: payouts } },
  };
}

async function post(payload: string, header: string) {
  return app.inject({
    method: 'POST',
    url: '/v1/webhooks/stripe',
    headers: { 'content-type': 'application/json', 'stripe-signature': header },
    payload,
  });
}

beforeAll(async () => {
  tdb = await startTestDatabase();
  await seedSample(tdb.db);
  workerPool = createDb({ url: tdb.urlFor('worker'), max: 2 });
  webPool = createDb({ url: tdb.urlFor('web'), max: 2 });

  app = await buildApp(config, {
    db: tdb.db,
    stripeWebhook: {
      workerDb: workerPool.db,
      // A real client: only `constructEvent` is exercised, and it never calls out.
      stripe: createStripeClient({
        secretKey: 'sk_test_unused',
        webhookSecret: WEBHOOK_SECRET,
      }),
    },
  });

  for (const id of [SELLER, BUYER]) {
    await tdb.db.execute(
      `insert into app.users (id, name, email) values ('${id}', '${id}', '${id}@example.invalid')`,
    );
  }
}, 180_000);

afterAll(async () => {
  await app.close();
  await workerPool.close();
  await webPool.close();
  await tdb.close();
});

beforeEach(async () => {
  await tdb.db.execute(
    `truncate app.webhook_events, app.seller_accounts, app.audit_log, app.orders, app.listings cascade`,
  );
  await workerPool.db.execute(
    `insert into app.seller_accounts (user_id, stripe_account_id) values ('${SELLER}', '${ACCOUNT}')`,
  );
});

describe('a delivery we cannot verify', () => {
  it('is refused without a signature at all', async () => {
    const res = await app.inject({
      method: 'POST',
      url: '/v1/webhooks/stripe',
      headers: { 'content-type': 'application/json' },
      payload: JSON.stringify(accountUpdated(ACCOUNT, true, true)),
    });
    expect(res.statusCode).toBe(400);
  });

  it('is refused when the signature was made with another secret', async () => {
    // AC-5.2: a forged signature is a 400. This is the whole security of the endpoint —
    // anybody on the internet can POST here, and only this makes it mean anything.
    const { payload, header } = delivery(accountUpdated(ACCOUNT, true, true), {
      secret: 'whsec_somebody_elses_secret',
    });
    const res = await post(payload, header);
    expect(res.statusCode).toBe(400);
    expect(res.json<{ error: string }>().error).toBe('invalid_signature');
  });

  it('is refused when the body has been altered after signing', async () => {
    // The reason the raw bytes are kept. Signing "charges_enabled: false" and delivering
    // "true" is exactly the attack, and re-serialising the parsed body would have hidden it.
    const { header } = delivery(accountUpdated(ACCOUNT, false, false));
    const tampered = JSON.stringify(accountUpdated(ACCOUNT, true, true));
    const res = await post(tampered, header);
    expect(res.statusCode).toBe(400);
  });

  it('is refused when the timestamp is old enough to be a replay', async () => {
    // Stripe's tolerance is five minutes. A captured delivery from last week is not a
    // delivery.
    const { payload, header } = delivery(accountUpdated(ACCOUNT, true, true), {
      at: Math.floor(Date.now() / 1000) - 60 * 60,
    });
    const res = await post(payload, header);
    expect(res.statusCode).toBe(400);
  });

  it('changes nothing when it is refused', async () => {
    const { payload, header } = delivery(accountUpdated(ACCOUNT, true, true), {
      secret: 'whsec_wrong',
    });
    await post(payload, header);

    const [row] = await workerPool.db.execute<{ charges_enabled: boolean }>(
      `select charges_enabled from app.seller_accounts where stripe_account_id = '${ACCOUNT}'`,
    );
    expect(row?.charges_enabled).toBe(false);
    const events = await workerPool.db.execute(`select id from app.webhook_events`);
    expect(events).toHaveLength(0);
  });
});

describe('a delivery we can verify', () => {
  it('records what Stripe said about the account', async () => {
    const { payload, header } = delivery(accountUpdated(ACCOUNT, true, true));
    const res = await post(payload, header);

    expect(res.statusCode).toBe(200);
    expect(res.json()).toEqual({ received: true });

    const [row] = await workerPool.db.execute<{
      charges_enabled: boolean;
      payouts_enabled: boolean;
    }>(
      `select charges_enabled, payouts_enabled from app.seller_accounts
        where stripe_account_id = '${ACCOUNT}'`,
    );
    expect(row).toMatchObject({ charges_enabled: true, payouts_enabled: true });
  });

  it('treats anything that is not exactly true as false', async () => {
    // The capability arrives over the network from a service across an API version boundary
    // we pin and they move. Being generous here means somebody taking payments they cannot be
    // paid for.
    const event = {
      id: 'evt_odd',
      object: 'event',
      type: 'account.updated',
      data: { object: { id: ACCOUNT, charges_enabled: 'yes', payouts_enabled: 1 } },
    };
    const { payload, header } = delivery(event);
    await post(payload, header);

    const [row] = await workerPool.db.execute<{
      charges_enabled: boolean;
      payouts_enabled: boolean;
    }>(
      `select charges_enabled, payouts_enabled from app.seller_accounts
        where stripe_account_id = '${ACCOUNT}'`,
    );
    expect(row).toMatchObject({ charges_enabled: false, payouts_enabled: false });
  });

  it('is a no-op the second time, and says so', async () => {
    // AC-5.2: a replayed event does nothing. Stripe retries anything that is not a prompt
    // 2xx, so the same delivery arriving twice is normal rather than suspicious.
    const { payload, header } = delivery(accountUpdated(ACCOUNT, true, true, 'evt_replay'));

    const first = await post(payload, header);
    expect(first.json()).toEqual({ received: true });

    // Somebody turns the account off underneath us; a replay must not turn it back on.
    await workerPool.db.execute(
      `update app.seller_accounts set charges_enabled = false where stripe_account_id = '${ACCOUNT}'`,
    );

    const second = await post(payload, header);
    expect(second.statusCode).toBe(200);
    expect(second.json()).toEqual({ received: true, duplicate: true });

    const [row] = await workerPool.db.execute<{ charges_enabled: boolean }>(
      `select charges_enabled from app.seller_accounts where stripe_account_id = '${ACCOUNT}'`,
    );
    expect(row?.charges_enabled, 'the replay re-applied the event').toBe(false);
  });

  it('acknowledges an event type it does not handle, rather than letting Stripe retry for days', async () => {
    const event = {
      id: 'evt_unknown',
      object: 'event',
      type: 'invoice.payment_succeeded',
      data: { object: { id: 'in_1' } },
    };
    const { payload, header } = delivery(event);
    const res = await post(payload, header);

    expect(res.statusCode).toBe(200);
    // Claimed and marked done: "we received this and chose to ignore it" is a true and useful
    // thing for the table to say.
    const [row] = await workerPool.db.execute<{ type: string; processed_at: string | null }>(
      `select type, processed_at from app.webhook_events where event_id = 'evt_unknown'`,
    );
    expect(row?.type).toBe('invoice.payment_succeeded');
    expect(row?.processed_at).not.toBeNull();
  });

  it('shrugs at an account we have never heard of', async () => {
    // A connected account created and abandoned before we recorded it. Nothing to update and
    // nothing to complain about — certainly not a 500 that makes Stripe retry for a day.
    const { payload, header } = delivery(accountUpdated('acct_unknown', true, true, 'evt_ghost'));
    const res = await post(payload, header);
    expect(res.statusCode).toBe(200);
  });
});

describe('what a session can do with this table', () => {
  it('nothing at all', async () => {
    // A webhook is not a session. Migration 0041 gives the web role no privilege on
    // `webhook_events`, so the idempotency record cannot be read, forged or cleared by
    // anything a browser can reach.
    let refused = false;
    try {
      await webPool.db.execute(`select id from app.webhook_events`);
    } catch {
      refused = true;
    }
    expect(refused).toBe(true);
  });
});

/**
 * Refunds and chargebacks (FR-5.5, T11).
 *
 * Signed for real, like everything else in this file. What is under test is the half that
 * decides whether to believe a claim that money moved *back* — the same question as `paid`,
 * asked in the other direction, and with the same answer: only a verified webhook may say so.
 */
const BUYER = 'webhook-buyer';

/** A paid order, built on the roles actually permitted to build one. */
async function aPaidOrder(paymentIntentId: string): Promise<string> {
  const [variant] = await tdb.db.execute<{ id: string }>(
    `select id from app.card_variants limit 1`,
  );
  const listing = await createListing(webPool.db, SELLER, {
    cardVariantId: String(variant?.id),
    condition: 'nm',
    priceCents: 2000,
    quantity: 1,
  });
  await setListingStatus(webPool.db, SELLER, listing.id, 'active');
  const order = await createOrder(webPool.db, BUYER, {
    sellerId: SELLER,
    listingId: listing.id,
    cardVariantId: String(variant?.id),
    condition: 'nm',
    quantity: 1,
    amountCents: 2000,
    feeCents: 100,
    currency: 'USD',
  });
  await markOrderPaid(workerPool.db, {
    orderId: order.id,
    paymentIntentId,
    checkoutSessionId: `cs_${paymentIntentId}`,
  });
  return order.id;
}

function refunded(paymentIntentId: string, eventId: string, amountRefunded = 2000) {
  return {
    id: eventId,
    object: 'event',
    type: 'charge.refunded',
    data: {
      object: {
        id: 'ch_1',
        object: 'charge',
        payment_intent: paymentIntentId,
        amount: 2000,
        amount_refunded: amountRefunded,
      },
    },
  };
}

function disputeOpened(paymentIntentId: string, eventId: string) {
  return {
    id: eventId,
    object: 'event',
    type: 'charge.dispute.created',
    data: {
      object: {
        id: 'dp_1',
        object: 'dispute',
        payment_intent: paymentIntentId,
        reason: 'product_not_received',
      },
    },
  };
}

async function statusOf(orderId: string): Promise<string> {
  const [row] = await workerPool.db.execute<{ status: string }>(
    `select status from app.orders where id = '${orderId}'`,
  );
  return String(row?.status);
}

describe('money going back', () => {
  it('marks an order refunded when Stripe says the whole charge went back', async () => {
    const orderId = await aPaidOrder('pi_wh_refund');
    const { payload, header } = delivery(refunded('pi_wh_refund', 'evt_refund_1'));

    expect((await post(payload, header)).statusCode).toBe(200);
    expect(await statusOf(orderId)).toBe('refunded');
  });

  it('leaves a partly refunded order where it is', async () => {
    /**
     * A partial refund is not a refunded order. The buyer has not been made whole and the sale
     * has not been undone — it wants a person, not a status change.
     */
    const orderId = await aPaidOrder('pi_wh_partial');
    const { payload, header } = delivery(refunded('pi_wh_partial', 'evt_refund_2', 500));

    expect((await post(payload, header)).statusCode).toBe(200);
    expect(await statusOf(orderId)).toBe('paid');
  });

  it('shrugs at a refund for a payment we have no order for', async () => {
    const { payload, header } = delivery(refunded('pi_not_ours', 'evt_refund_3'));
    expect((await post(payload, header)).statusCode).toBe(200);
  });

  it('will not refund on a forged signature', async () => {
    // The whole marketplace in one assertion, in the direction that gives money away.
    const orderId = await aPaidOrder('pi_wh_forged');
    const { payload, header } = delivery(refunded('pi_wh_forged', 'evt_refund_4'), {
      secret: 'whsec_somebody_elses_secret',
    });

    expect((await post(payload, header)).statusCode).toBe(400);
    expect(await statusOf(orderId)).toBe('paid');
  });
});

describe('a chargeback', () => {
  it('moves the order to disputed and says which reason the bank gave', async () => {
    const orderId = await aPaidOrder('pi_wh_dispute');
    const { payload, header } = delivery(disputeOpened('pi_wh_dispute', 'evt_dispute_1'));

    expect((await post(payload, header)).statusCode).toBe(200);
    expect(await statusOf(orderId)).toBe('disputed');

    const [entry] = await workerPool.db.execute<{ diff: { reason?: string } }>(
      `select diff from app.audit_log where action = 'order.chargeback'`,
    );
    // Stripe's own vocabulary, prefixed so nobody reads it as something a person typed.
    expect(entry?.diff.reason).toBe('chargeback:product_not_received');
  });

  it('reaches an order that was only just paid for', async () => {
    /**
     * The gap this found. `stripe` was originally an actor for `disputed` only from
     * `completed`, so a chargeback on a freshly paid order was refused by the state machine
     * and the handler could do nothing with it. A buyer goes to their bank when the charge
     * appears on a statement, not when we decide the sale is finished.
     */
    const orderId = await aPaidOrder('pi_wh_early');
    const { payload, header } = delivery(disputeOpened('pi_wh_early', 'evt_dispute_2'));

    await post(payload, header);
    expect(await statusOf(orderId)).toBe('disputed');
  });
});
