import {
  booleanStringSchema,
  logLevelSchema,
  nodeEnvSchema,
  optional,
  parseEnv,
  portSchema,
} from '@gth/core';
import { z } from 'zod';

const apiEnvSchema = z.object({
  NODE_ENV: nodeEnvSchema,
  LOG_LEVEL: logLevelSchema,
  API_HOST: z.string().min(1).default('127.0.0.1'),
  API_PORT: portSchema.default(4000),
  // Only true behind our own reverse proxy (Caddy), otherwise X-Forwarded-For is spoofable.
  API_TRUST_PROXY: booleanStringSchema,
  API_RATE_LIMIT_MAX: z.coerce.number().int().positive().default(120),
  DATABASE_URL_READONLY: z
    .string()
    .startsWith('postgres', 'must be a postgres connection string')
    .default('postgres://app_readonly:change-me@127.0.0.1:5432/gth'),
  DATABASE_URL_WEB: z
    .string()
    .startsWith('postgres', 'must be a postgres connection string')
    .default('postgres://app_web:change-me@127.0.0.1:5432/gth'),
  DATABASE_URL_WORKER: z
    .string()
    .startsWith('postgres', 'must be a postgres connection string')
    .default('postgres://app_worker:change-me@127.0.0.1:5432/gth'),
  DB_POOL_MAX: z.coerce.number().int().min(1).max(50).default(10),
  /** Keys API-key hashes; generated by `pnpm env:init` (SR-X.17). */
  TOKEN_PEPPER: z.string().min(32).default('dev-only-insecure-pepper-change-me-32+'),
  /**
   * Field encryption (SR-1.6, SR-4.2). `{"kid": "<base64 32 bytes>"}` plus the id to write
   * with. The default is a fixed development key and is refused in production by the check
   * below — a break seed encrypted with a key that is in the repository is not encrypted.
   */
  DATA_ENCRYPTION_KEYS: z.string().default(`{"dev":"${Buffer.alloc(32, 7).toString('base64')}"}`),
  DATA_ENCRYPTION_ACTIVE_KID: z.string().min(1).default('dev'),
  /** Optional: creator/ops Discord webhook used for the discord_webhook channel. */
  DISCORD_ALERT_WEBHOOK_URL: optional(z.url()),

  // Auth (plan §10, FR-1.10). The secret must be >=32 chars of CSPRNG output (SR-X.16).
  API_BASE_URL: z.url().default('http://127.0.0.1:4000'),
  APP_BASE_URL: z.url().default('http://127.0.0.1:3000'),
  BETTER_AUTH_SECRET: z.string().min(32).default('dev-only-insecure-secret-change-me-32+'),
  // Optional settings: an empty value means "not configured" (see optional() in @gth/core).
  DISCORD_CLIENT_ID: optional(z.string().min(1)),
  DISCORD_CLIENT_SECRET: optional(z.string().min(1)),
  SMTP_URL: optional(z.string().startsWith('smtp')),
  EMAIL_FROM: z.string().default('gundam-tcg-hub <no-reply@localhost>'),
});

export type ApiConfig = z.infer<typeof apiEnvSchema>;

export function loadConfig(source: Record<string, string | undefined> = process.env): ApiConfig {
  const config = parseEnv(apiEnvSchema, source);

  // Refuse to start in production with any of the development defaults. Each of these is a
  // value that is in the repository, and a secret in the repository is not a secret — the
  // right place to find that out is at boot, not from an incident.
  if (config.NODE_ENV === 'production') {
    const insecure = [
      ['TOKEN_PEPPER', config.TOKEN_PEPPER.startsWith('dev-only-insecure')],
      ['BETTER_AUTH_SECRET', config.BETTER_AUTH_SECRET.startsWith('dev-only-insecure')],
      ['DATA_ENCRYPTION_ACTIVE_KID', config.DATA_ENCRYPTION_ACTIVE_KID === 'dev'],
    ].filter(([, isDefault]) => isDefault);

    if (insecure.length > 0) {
      throw new Error(
        `refusing to start: ${insecure.map(([name]) => String(name)).join(', ')} ` +
          'still hold their development defaults',
      );
    }
  }

  return config;
}
