import { isIP } from 'node:net';
import {
  booleanStringSchema,
  logLevelSchema,
  nodeEnvSchema,
  optional,
  parseEnv,
  portSchema,
} from '@gth/core';
import { z } from 'zod';

const apiEnvSchema = z.object({
  NODE_ENV: nodeEnvSchema,
  LOG_LEVEL: logLevelSchema,
  API_HOST: z.string().min(1).default('127.0.0.1'),
  API_PORT: portSchema.default(4000),
  // Only true behind our own reverse proxy (Caddy), otherwise X-Forwarded-For is spoofable.
  API_TRUST_PROXY: booleanStringSchema,
  API_RATE_LIMIT_MAX: z.coerce.number().int().positive().default(120),
  DATABASE_URL_READONLY: z
    .string()
    .startsWith('postgres', 'must be a postgres connection string')
    .default('postgres://app_readonly:change-me@127.0.0.1:5432/gth'),
  DATABASE_URL_WEB: z
    .string()
    .startsWith('postgres', 'must be a postgres connection string')
    .default('postgres://app_web:change-me@127.0.0.1:5432/gth'),
  DATABASE_URL_WORKER: z
    .string()
    .startsWith('postgres', 'must be a postgres connection string')
    .default('postgres://app_worker:change-me@127.0.0.1:5432/gth'),
  DB_POOL_MAX: z.coerce.number().int().min(1).max(50).default(10),
  /** Keys API-key hashes; generated by `pnpm env:init` (SR-X.17). */
  TOKEN_PEPPER: z.string().min(32).default('dev-only-insecure-pepper-change-me-32+'),
  /**
   * Field encryption (SR-1.6, SR-4.2). `{"kid": "<base64 32 bytes>"}` plus the id to write
   * with. The default is a fixed development key and is refused in production by the check
   * below — a break seed encrypted with a key that is in the repository is not encrypted.
   */
  DATA_ENCRYPTION_KEYS: z.string().default(`{"dev":"${Buffer.alloc(32, 7).toString('base64')}"}`),
  DATA_ENCRYPTION_ACTIVE_KID: z.string().min(1).default('dev'),
  /** Optional: creator/ops Discord webhook used for the discord_webhook channel. */
  DISCORD_ALERT_WEBHOOK_URL: optional(z.url()),

  // Auth (plan §10, FR-1.10). The secret must be >=32 chars of CSPRNG output (SR-X.16).
  API_BASE_URL: z.url().default('http://127.0.0.1:4000'),
  /**
   * `localhost`, not `127.0.0.1`, and the difference is not cosmetic.
   *
   * This value is the base for every URL we hand to somebody else's browser — Stripe's Checkout
   * `success_url`, the onboarding `return_url` and `refresh_url`, the links in emails. On a
   * Windows host running the stack in WSL2, **`127.0.0.1:3000` is not reachable from the
   * browser at all**: WSL forwards the `localhost` name and not the loopback address. So a
   * buyer would complete a payment, Stripe would redirect exactly as instructed, and the tab
   * would fail to connect — which looks like our page crashing rather than a configuration
   * mistake. It cost two misdiagnosed bug reports before anyone tested from the host side.
   *
   * It also matches `WEBAUTHN_ORIGIN`, which has to be a hostname because WebAuthn refuses an
   * IP address as a relying party. Two defaults that disagreed about the same site were a trap
   * on their own.
   *
   * `API_BASE_URL` above stays on the loopback address deliberately: it is called server to
   * server and by the CI harness, never typed into a browser by anything we do not control.
   */
  APP_BASE_URL: z.url().default('http://localhost:3000'),
  BETTER_AUTH_SECRET: z.string().min(32).default('dev-only-insecure-secret-change-me-32+'),
  // Optional settings: an empty value means "not configured" (see optional() in @gth/core).
  DISCORD_CLIENT_ID: optional(z.string().min(1)),
  DISCORD_CLIENT_SECRET: optional(z.string().min(1)),
  SMTP_URL: optional(z.string().startsWith('smtp')),
  EMAIL_FROM: z.string().default('gundam-tcg-hub <no-reply@localhost>'),

  /**
   * WebAuthn relying party (ADR-025).
   *
   * `localhost`, not `127.0.0.1`: WebAuthn forbids an IP address as an RP ID, so in local
   * development passkeys only work with the site opened at http://localhost:3000. The origin
   * is the *site* — where the browser runs the ceremony — never the API.
   */
  WEBAUTHN_RP_ID: z.string().min(1).default('localhost'),
  WEBAUTHN_RP_NAME: z.string().min(1).max(64).default('Gundam TCG Hub'),
  WEBAUTHN_ORIGIN: z.url().default('http://localhost:3000'),

  /**
   * Stripe (Phase 5, ADR-011). All optional: the marketplace is simply off until they are
   * set, and every other part of this API runs without them.
   *
   * There is no development default, and there will not be one. A default elsewhere in this
   * file is a weak key refused in production; a default here would be somebody else's Stripe
   * account. The *shapes* are pinned instead, because `sk_live_` sitting where `sk_test_`
   * belongs is exactly the mistake worth catching at boot rather than at the first charge.
   */
  STRIPE_SECRET_KEY: optional(z.string().regex(/^sk_(test|live)_[A-Za-z0-9]+$/u)),
  /**
   * Per-service keys, each optional and each falling back to `STRIPE_SECRET_KEY` (SR-5.3).
   *
   * One key doing every job means a compromise of either process can do the other's work. Split,
   * the blast radius shrinks to something specific: the **web** key may create Checkout sessions
   * and connected accounts but **cannot issue a refund**, so a compromised web process cannot
   * move money out; the **worker** key may refund and read but **cannot create a Checkout
   * session**, so a compromised worker cannot take money in.
   *
   * `rk_` as well as `sk_`, because a restricted key is what this is for — but `sk_` stays valid
   * so that a deployment which has not split its keys yet keeps working instead of refusing to
   * boot. The fallback is deliberate and is resolved in one place, `stripeKeyFor`.
   *
   * Both still need account read **and** write, which is not laziness: the web side creates the
   * connected account and sets its payout schedule at creation (FR-5.6), and the worker releases
   * that hold later and re-reads capabilities from webhooks. Narrowing either to read-only breaks
   * onboarding or the release job.
   */
  STRIPE_SECRET_KEY_WEB: optional(z.string().regex(/^(sk|rk)_(test|live)_[A-Za-z0-9]+$/u)),
  STRIPE_SECRET_KEY_WORKER: optional(z.string().regex(/^(sk|rk)_(test|live)_[A-Za-z0-9]+$/u)),
  STRIPE_PUBLISHABLE_KEY: optional(z.string().regex(/^pk_(test|live)_[A-Za-z0-9]+$/u)),
  /** From `stripe listen` locally, or the endpoint's signing secret in the dashboard. */
  STRIPE_WEBHOOK_SECRET: optional(z.string().startsWith('whsec_')),
  /**
   * The **v2 event destination's** signing secret — a different feed, a different secret.
   *
   * Connect capability changes arrive here now that accounts are v2 (ADR-045). Separate from
   * `STRIPE_WEBHOOK_SECRET` on purpose: one secret verifying two feeds would mean a
   * misconfiguration on either could let an event be trusted on the wrong endpoint.
   *
   * Locally: `stripe listen --all-thin --events-from @accounts`. In a deployment:
   * `pnpm stripe:destination`, which creates the destination and prints the secret once.
   */
  STRIPE_V2_WEBHOOK_SECRET: optional(z.string().startsWith('whsec_')),
  /**
   * Our cut, in basis points (FR-5.3). 500 = 5%.
   *
   * Basis points rather than a percentage float: money that has been through a float is a
   * number nobody can reconcile, and this one is subtracted from what a seller is owed.
   */
  MARKETPLACE_FEE_BPS: z.coerce.number().int().min(0).max(2000).default(500),

  /**
   * Listing photos (Phase 5, SR-5.5, open item O4).
   *
   * All optional, like Stripe: uploads are simply off until storage is configured, and every
   * other part of this API runs without it. A route that exists and answers 500 because a
   * bucket is missing is worse than one that is not mounted.
   *
   * No default for the credentials, for the same reason there is no default Stripe key.
   */
  S3_ENDPOINT: optional(z.url()),
  S3_BUCKET: optional(z.string().regex(/^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$/u)),
  S3_REGION: z.string().min(1).default('us-east-1'),
  S3_ACCESS_KEY_ID: optional(z.string().min(3)),
  S3_SECRET_ACCESS_KEY: optional(z.string().min(8)),

  /**
   * The virus scanner (SR-5.5).
   *
   * Optional, and its absence is **not** permission to skip scanning: the pipeline leaves a
   * photo `pending` when it cannot get a verdict. Configuring this is what lets an upload
   * finish, not what makes it safe.
   */
  CLAMAV_HOST: optional(z.string().min(1)),
  CLAMAV_PORT: z.coerce.number().int().min(1).max(65_535).default(3310),
});

export type ApiConfig = z.infer<typeof apiEnvSchema>;

/**
 * Is this relying-party configuration one a browser will actually accept?
 *
 * Checked at boot because every failure mode here is silent until someone tries to sign in:
 * an IP address as the RP ID, or an origin on a different domain from the RP ID, and the
 * browser simply refuses every passkey — including an admin's, which locks them out of the
 * console with nothing in the logs to say why.
 */
export function webAuthnProblem(
  config: Pick<ApiConfig, 'WEBAUTHN_RP_ID' | 'WEBAUTHN_ORIGIN'>,
): string | null {
  const rpID = config.WEBAUTHN_RP_ID.toLowerCase();
  // Node's own parser rather than a pattern: it knows IPv6 and every IPv4 spelling.
  if (isIP(rpID) !== 0 || rpID.includes(':')) {
    return 'WEBAUTHN_RP_ID must be a domain name; WebAuthn does not allow an IP address';
  }
  const host = new URL(config.WEBAUTHN_ORIGIN).hostname.toLowerCase();
  if (host !== rpID && !host.endsWith(`.${rpID}`)) {
    return `WEBAUTHN_ORIGIN (${host}) must be ${rpID} or a subdomain of it`;
  }
  return null;
}

/** Which service is asking for a Stripe key. Not a label — it decides what the key may do. */
export type StripeRole = 'web' | 'worker';

/**
 * The key a service should use, with the fallback stated once (SR-5.3).
 *
 * A per-service key if one is configured, otherwise the shared `STRIPE_SECRET_KEY`. The fallback
 * exists so that splitting the keys is a deployment step rather than a breaking change: a host
 * that has not done it yet keeps working exactly as before.
 *
 * Returning `undefined` means Stripe is not configured at all, which the caller already treats as
 * "the marketplace routes do not exist" — better than routes that answer 500 for a missing secret.
 */
export function stripeKeyFor(config: ApiConfig, role: StripeRole): string | undefined {
  const specific = role === 'web' ? config.STRIPE_SECRET_KEY_WEB : config.STRIPE_SECRET_KEY_WORKER;
  return specific ?? config.STRIPE_SECRET_KEY;
}

/**
 * Whether the keys are actually split, for the boot log.
 *
 * Worth saying out loud on every start. An operator who believes they have separated their keys
 * and has not is in the worst position: they have the audit answer without the control, and
 * nothing anywhere would otherwise contradict them.
 */
export function stripeKeysAreSplit(config: ApiConfig): boolean {
  const web = config.STRIPE_SECRET_KEY_WEB;
  const worker = config.STRIPE_SECRET_KEY_WORKER;
  return web !== undefined && worker !== undefined && web !== worker;
}

export function loadConfig(source: Record<string, string | undefined> = process.env): ApiConfig {
  const config = parseEnv(apiEnvSchema, source);

  const webAuthn = webAuthnProblem(config);
  if (webAuthn) throw new Error(`refusing to start: ${webAuthn}`);

  // Refuse to start in production with any of the development defaults. Each of these is a
  // value that is in the repository, and a secret in the repository is not a secret — the
  // right place to find that out is at boot, not from an incident.
  if (config.NODE_ENV === 'production') {
    const insecure = [
      ['TOKEN_PEPPER', config.TOKEN_PEPPER.startsWith('dev-only-insecure')],
      ['BETTER_AUTH_SECRET', config.BETTER_AUTH_SECRET.startsWith('dev-only-insecure')],
      ['DATA_ENCRYPTION_ACTIVE_KID', config.DATA_ENCRYPTION_ACTIVE_KID === 'dev'],
      // Not the WebAuthn settings, deliberately. CI runs a production build on
      // http://localhost, and a `localhost` relying party left in place on a real domain fails
      // *closed* — browsers refuse to use it, so admins are locked out, not let in. That is an
      // operations failure the runbook covers, not a secret in the repository; the structural
      // check above is the one that catches a configuration that could never work.
    ].filter(([, isDefault]) => isDefault);

    if (insecure.length > 0) {
      throw new Error(
        `refusing to start: ${insecure.map(([name]) => String(name)).join(', ')} ` +
          'still hold their development defaults',
      );
    }
  }

  return config;
}
