#!/usr/bin/env bash
# Create a local .env with freshly generated secrets (plan §9.6, SR-0.12, SR-0.16).
# Never overwrites an existing .env. Values never leave this machine.
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo ".env already exists - leaving it alone. Delete it first to regenerate."
  exit 0
fi

rand_hex() { openssl rand -hex 24; }

PG_SUPERPASSWORD="$(rand_hex)"
PG_MIGRATOR_PASSWORD="$(rand_hex)"
PG_WEB_PASSWORD="$(rand_hex)"
PG_WORKER_PASSWORD="$(rand_hex)"
PG_READONLY_PASSWORD="$(rand_hex)"
TOKEN_PEPPER="$(openssl rand -base64 32)"
BETTER_AUTH_SECRET="$(openssl rand -base64 32)"
# Encrypts database fields that must stay secret even in a backup -- today, a break's server
# seed. Keyed by id so keys can rotate without re-encrypting anything in a hurry.
DATA_ENCRYPTION_KEY="$(openssl rand -base64 32)"
# Object storage for listing photos. Local only: the bucket lives in a container on loopback.
S3_ACCESS_KEY_ID="gth$(openssl rand -hex 8)"
S3_SECRET_ACCESS_KEY="$(rand_hex)"

umask 077
cat > .env <<EOF
# Generated by scripts/init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Local dev only - never commit.
NODE_ENV=development
LOG_LEVEL=debug

API_HOST=127.0.0.1
API_PORT=4000
# The API sits behind the web app's proxy (and Caddy in production), so the real client IP
# arrives in X-Forwarded-For. Without this, every user shares one rate-limit bucket.
# Safe only because the proxy overwrites the header (see infra/caddy/Caddyfile).
API_TRUST_PROXY=true
API_RATE_LIMIT_MAX=120

PG_SUPERUSER=gth_admin
PG_SUPERPASSWORD=${PG_SUPERPASSWORD}
PG_DATABASE=gth
PG_MIGRATOR_PASSWORD=${PG_MIGRATOR_PASSWORD}
PG_WEB_PASSWORD=${PG_WEB_PASSWORD}
PG_WORKER_PASSWORD=${PG_WORKER_PASSWORD}
PG_READONLY_PASSWORD=${PG_READONLY_PASSWORD}
DATABASE_URL_MIGRATOR=postgres://app_migrator:${PG_MIGRATOR_PASSWORD}@127.0.0.1:5432/gth
DATABASE_URL_WEB=postgres://app_web:${PG_WEB_PASSWORD}@127.0.0.1:5432/gth
DATABASE_URL_WORKER=postgres://app_worker:${PG_WORKER_PASSWORD}@127.0.0.1:5432/gth
DATABASE_URL_READONLY=postgres://app_readonly:${PG_READONLY_PASSWORD}@127.0.0.1:5432/gth

TOKEN_PEPPER=${TOKEN_PEPPER}
# Single-quoted: this value is JSON, and some consumers of this file are shells. Unquoted,
# "set -a; . ./.env" strips the double quotes and hands the application {k1:...}, which is
# not JSON and fails at boot. Node's --env-file and dotenv both understand the quotes.
#
# (Those used to be backticks. Inside this unquoted heredoc that is command substitution, so
# generating the file ran them: "pnpm env:init" printed "command not found", the comment
# explaining the quoting arrived in .env with its own explanation deleted, and one of them
# sourced the .env being written. Quotes, never backticks, inside this heredoc.)
DATA_ENCRYPTION_KEYS='{"k1":"${DATA_ENCRYPTION_KEY}"}'
DATA_ENCRYPTION_ACTIVE_KID=k1

# Auth. Sign-in links are emailed via Mailpit locally: start it with
#   docker compose --env-file .env -f infra/compose/docker-compose.dev.yml --profile mail up -d
# then read the mail at http://127.0.0.1:8025
API_BASE_URL=http://127.0.0.1:4000
APP_BASE_URL=http://127.0.0.1:3000
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
SMTP_URL=smtp://127.0.0.1:1025
EMAIL_FROM="gundam-tcg-hub <no-reply@localhost>"
# Passkeys need a domain name, not an IP: open the site at http://localhost:3000 to use them.
WEBAUTHN_RP_ID=localhost
WEBAUTHN_ORIGIN=http://localhost:3000
# Discord OAuth: create an app at https://discord.com/developers/applications,
# add redirect URI http://127.0.0.1:4000/api/auth/callback/discord, then fill these in.
# DISCORD_CLIENT_ID=
# DISCORD_CLIENT_SECRET=

# Listing photos (Phase 5, SR-5.5). Start the containers with
#   docker compose --env-file .env -f infra/compose/docker-compose.dev.yml --profile photos up -d
# The bucket is private: uploads arrive by presigned PUT and leave by short-lived signed GET,
# and nothing is ever served from it directly.
S3_ENDPOINT=http://127.0.0.1:8000
S3_BUCKET=gth-photos
S3_REGION=us-east-1
S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
# Malware scanning. Without it, uploads stay pending rather than being approved unscanned.
CLAMAV_HOST=127.0.0.1
CLAMAV_PORT=3310

OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:4318
EOF

echo "Created .env (mode 600) with generated secrets."
