#!/usr/bin/env bash
# Create a local .env with freshly generated secrets (plan §9.6, SR-0.12, SR-0.16).
# Never overwrites an existing .env. Values never leave this machine.
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo ".env already exists - leaving it alone. Delete it first to regenerate."
  exit 0
fi

rand_hex() { openssl rand -hex 24; }

PG_SUPERPASSWORD="$(rand_hex)"
PG_MIGRATOR_PASSWORD="$(rand_hex)"
PG_WEB_PASSWORD="$(rand_hex)"
PG_WORKER_PASSWORD="$(rand_hex)"
PG_READONLY_PASSWORD="$(rand_hex)"
VALKEY_PASSWORD="$(rand_hex)"
TOKEN_PEPPER="$(openssl rand -base64 32)"

umask 077
cat > .env <<EOF
# Generated by scripts/init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Local dev only - never commit.
NODE_ENV=development
LOG_LEVEL=debug

API_HOST=127.0.0.1
API_PORT=4000
API_TRUST_PROXY=false
API_RATE_LIMIT_MAX=120

PG_SUPERUSER=gth_admin
PG_SUPERPASSWORD=${PG_SUPERPASSWORD}
PG_DATABASE=gth
PG_MIGRATOR_PASSWORD=${PG_MIGRATOR_PASSWORD}
PG_WEB_PASSWORD=${PG_WEB_PASSWORD}
PG_WORKER_PASSWORD=${PG_WORKER_PASSWORD}
PG_READONLY_PASSWORD=${PG_READONLY_PASSWORD}
DATABASE_URL_MIGRATOR=postgres://app_migrator:${PG_MIGRATOR_PASSWORD}@127.0.0.1:5432/gth
DATABASE_URL_WEB=postgres://app_web:${PG_WEB_PASSWORD}@127.0.0.1:5432/gth
DATABASE_URL_WORKER=postgres://app_worker:${PG_WORKER_PASSWORD}@127.0.0.1:5432/gth
DATABASE_URL_READONLY=postgres://app_readonly:${PG_READONLY_PASSWORD}@127.0.0.1:5432/gth

VALKEY_PASSWORD=${VALKEY_PASSWORD}
VALKEY_URL=redis://:${VALKEY_PASSWORD}@127.0.0.1:6379/0

TOKEN_PEPPER=${TOKEN_PEPPER}

OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:4318
EOF

echo "Created .env (mode 600) with generated secrets."
